name: hello
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: github action test
        run: echo gihub action Test
      - name : dir 출력
        run : ls -al
      - name : version
        run : java -version
